import { StyleSheet } from 'react-native';
import { COLORS, SPORT_COLORS } from './colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  centerContent: { justifyContent: 'center', alignItems: 'center' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 10 },
  title: { fontSize: 28, fontWeight: 'bold', color: COLORS.text },
  sortBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: COLORS.cardBg, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20 },
  sortText: { fontSize: 12, color: COLORS.primary },
  searchSection: { paddingHorizontal: 20, marginBottom: 12 },
  searchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.cardBg, borderRadius: 12, paddingHorizontal: 16, height: 46 },
  searchInput: { flex: 1, color: COLORS.text, fontSize: 16, marginLeft: 12 },
  filtersSection: { marginBottom: 16 },
  filterList: { paddingHorizontal: 20, gap: 10 },
  filterChip: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: COLORS.cardBg },
  filterChipActive: { backgroundColor: COLORS.primary },
  filterChipText: { color: COLORS.muted },
  filterChipTextActive: { color: '#fff' },
  listContent: { paddingHorizontal: 20, paddingBottom: 20 },
  activityCard: { backgroundColor: COLORS.cardBg, borderRadius: 16, marginBottom: 12, overflow: 'hidden' },
  activityContent: { padding: 16 },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  sportContainer: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  iconCircle: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  sportName: { fontSize: 16, fontWeight: 'bold', color: COLORS.text },
  activityTime: { fontSize: 12, color: COLORS.muted, marginTop: 2 },
  metricsContainer: { flexDirection: 'row', justifyContent: 'space-around', paddingVertical: 12, borderTopWidth: 1, borderBottomWidth: 1, borderColor: COLORS.border },
  metricItem: { alignItems: 'center', gap: 4 },
  metricValue: { fontSize: 14, fontWeight: 'bold', color: COLORS.text },
  metricLabel: { fontSize: 10, color: COLORS.muted },
  metricDivider: { width: 1, backgroundColor: COLORS.border },
  detailsRow: { flexDirection: 'row', gap: 16, marginTop: 12 },
  detailItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  detailText: { fontSize: 12, color: COLORS.muted },
  routeInfo: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: COLORS.border },
  routeText: { fontSize: 11, color: COLORS.muted },
  loadingText: { color: COLORS.muted, marginTop: 10 },
  emptyContainer: { alignItems: 'center', paddingVertical: 60 },
  emptyTitle: { fontSize: 18, fontWeight: 'bold', color: COLORS.text, marginTop: 16 },
  emptyText: { fontSize: 14, color: COLORS.muted, textAlign: 'center', marginTop: 8 },
});

export { SPORT_COLORS };